# AIRFIELD
# Database Configuration

common: &common
  encoding: utf8
  adapter: mysql2
  username: root
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *common
  database: airfield_dev

test:
  <<: *common
  database: airfield_test

production:
  <<: *common
  database: airfield_test
  host: production.database.on.heroku.com
  username: airfield
  password: fly1nGin+h3@ir
